2022-04-08 11:45:05,348 - INFO - 
Config:
'add_train': False
'batch_size': 64
'clean_data_path': None
'cur_time': '2022_04_08_11_45_03'
'data_path': './data/'
'do_continue_train': True
'do_figure_save': True
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0
'epoch': 20
'feature_columns': [1, 3, 6]
'figure_save_path': './figure/'
'frame': 'pytorch'
'hidden_size': 64
'input_size': 3
'label_columns': [1]
'learning_rate': 0.01
'load_logger': <bound method Config.load_logger of <path_config.Config object at 0x00000126CE439EE0>>
'log_save_path': './log/2022_04_08_11_45_03_pytorch/'
'lstm_layers': 1
'mean': None
'model_name': '_20220408.pth'
'model_postfix': {'pytorch': '.pth'}
'model_save_path': './checkpoint/'
'out_size': 1
'patience': 5
'predict_day': 1
'random_seed': 42
'read_data_path': None
'seq': None
'shuffle_train_data': False
'std': None
'stock_date': None
'stock_name': None
'test_data': None
'time_step': 30
'train_data_rate': 0.95
'train_loss_path': './train_loss'
'url_path': './data/url.csv'
'use_cuda': True
'valid_ac_path': './valid_ac'
'valid_data_rate': 0.15
'valid_loss_path': './valid_loss'
2022-04-08 11:45:08,987 - INFO - 正在进行预测请稍等...
2022-04-08 11:45:16,705 - INFO - Accuracy: 56.18%
2022-04-08 11:45:16,709 - INFO - The predicted stock trend is: ['down']
2022-04-08 11:45:17,114 - ERROR - Run Error
Traceback (most recent call last):
  File "e:\StockCalculate\main.py", line 186, in main
    plt.plot(len(label_Y), label_Y, 'b', label='Historical net worth')
  File "C:\python3.8\lib\site-packages\matplotlib\pyplot.py", line 3019, in plot
    return gca().plot(
  File "C:\python3.8\lib\site-packages\matplotlib\axes\_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\python3.8\lib\site-packages\matplotlib\axes\_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\python3.8\lib\site-packages\matplotlib\axes\_base.py", line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1,) and (30,)
